# site settings
title: Almaraz Lawn Care
subtitle: lawn care services
email: hector@almarazlawn.com
description: Almaraz Lawn Care services - Since 2022.<br />Family owned and operated.
baseurl: "/almarazlawn" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address: 1304 Hillside Drive
city: Gainesville
state: TX
zip_code: 76240
country: United States of America
phone: (940) 443-4037

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  Facebook: https://www.facebook.com/amber.nichole.9066389
  Instagram: https://www.instagram.com/almarazlawn
  Yelp: https://www.yelp.com/biz/almarazlawn
  Twitter: https://twitter.com/almarazlawn

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
